/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ice.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.ice.fsm.ui.internal.FsmActivator;

public class FsmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FsmActivator.getInstance().getInjector("org.xtext.ice.Fsm");
	}

}
