/**
 * generated by Xtext 2.25.0
 */
package org.xtext.ice.generator;

import fr.ice.fsm.model.Fsm;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class FsmGenerator extends AbstractGenerator {
  private FSMvisitor myVisitor;
  
  private FsmInterpreter myInterpreter;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _get = resource.getContents().get(0);
    final Fsm myFsm = ((Fsm) _get);
    fsmJavaCompiler _fsmJavaCompiler = new fsmJavaCompiler();
    this.myVisitor = _fsmJavaCompiler;
    FsmInterpreter _fsmInterpreter = new FsmInterpreter();
    this.myInterpreter = _fsmInterpreter;
    fsa.generateFile("main.java", this.myVisitor.compile(myFsm));
    this.myInterpreter.interpret(myFsm);
  }
}
