/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ice.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FsmUiModule extends AbstractFsmUiModule {

	public FsmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
