/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ice.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.ice.FsmRuntimeModule;
import org.xtext.ice.FsmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FsmIdeSetup extends FsmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FsmRuntimeModule(), new FsmIdeModule()));
	}
	
}
